// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddMessageRequest struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMessageRequest) Reset()         { *m = AddMessageRequest{} }
func (m *AddMessageRequest) String() string { return proto.CompactTextString(m) }
func (*AddMessageRequest) ProtoMessage()    {}
func (*AddMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *AddMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMessageRequest.Unmarshal(m, b)
}
func (m *AddMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMessageRequest.Marshal(b, m, deterministic)
}
func (m *AddMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMessageRequest.Merge(m, src)
}
func (m *AddMessageRequest) XXX_Size() int {
	return xxx_messageInfo_AddMessageRequest.Size(m)
}
func (m *AddMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMessageRequest proto.InternalMessageInfo

func (m *AddMessageRequest) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *AddMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMessageResponse) Reset()         { *m = AddMessageResponse{} }
func (m *AddMessageResponse) String() string { return proto.CompactTextString(m) }
func (*AddMessageResponse) ProtoMessage()    {}
func (*AddMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *AddMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMessageResponse.Unmarshal(m, b)
}
func (m *AddMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMessageResponse.Marshal(b, m, deterministic)
}
func (m *AddMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMessageResponse.Merge(m, src)
}
func (m *AddMessageResponse) XXX_Size() int {
	return xxx_messageInfo_AddMessageResponse.Size(m)
}
func (m *AddMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMessageResponse proto.InternalMessageInfo

type GetMessagesRequest struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessagesRequest) Reset()         { *m = GetMessagesRequest{} }
func (m *GetMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessagesRequest) ProtoMessage()    {}
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *GetMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesRequest.Unmarshal(m, b)
}
func (m *GetMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesRequest.Marshal(b, m, deterministic)
}
func (m *GetMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesRequest.Merge(m, src)
}
func (m *GetMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessagesRequest.Size(m)
}
func (m *GetMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesRequest proto.InternalMessageInfo

func (m *GetMessagesRequest) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

type GetMessagesResponse struct {
	Messages             []string `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessagesResponse) Reset()         { *m = GetMessagesResponse{} }
func (m *GetMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessagesResponse) ProtoMessage()    {}
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *GetMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesResponse.Unmarshal(m, b)
}
func (m *GetMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesResponse.Marshal(b, m, deterministic)
}
func (m *GetMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesResponse.Merge(m, src)
}
func (m *GetMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessagesResponse.Size(m)
}
func (m *GetMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesResponse proto.InternalMessageInfo

func (m *GetMessagesResponse) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

type GetChatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatsRequest) Reset()         { *m = GetChatsRequest{} }
func (m *GetChatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetChatsRequest) ProtoMessage()    {}
func (*GetChatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *GetChatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatsRequest.Unmarshal(m, b)
}
func (m *GetChatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatsRequest.Marshal(b, m, deterministic)
}
func (m *GetChatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatsRequest.Merge(m, src)
}
func (m *GetChatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetChatsRequest.Size(m)
}
func (m *GetChatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatsRequest proto.InternalMessageInfo

type GetChatsResponse struct {
	Chats                []string `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatsResponse) Reset()         { *m = GetChatsResponse{} }
func (m *GetChatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetChatsResponse) ProtoMessage()    {}
func (*GetChatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *GetChatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatsResponse.Unmarshal(m, b)
}
func (m *GetChatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatsResponse.Marshal(b, m, deterministic)
}
func (m *GetChatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatsResponse.Merge(m, src)
}
func (m *GetChatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetChatsResponse.Size(m)
}
func (m *GetChatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatsResponse proto.InternalMessageInfo

func (m *GetChatsResponse) GetChats() []string {
	if m != nil {
		return m.Chats
	}
	return nil
}

func init() {
	proto.RegisterType((*AddMessageRequest)(nil), "chat.AddMessageRequest")
	proto.RegisterType((*AddMessageResponse)(nil), "chat.AddMessageResponse")
	proto.RegisterType((*GetMessagesRequest)(nil), "chat.GetMessagesRequest")
	proto.RegisterType((*GetMessagesResponse)(nil), "chat.GetMessagesResponse")
	proto.RegisterType((*GetChatsRequest)(nil), "chat.GetChatsRequest")
	proto.RegisterType((*GetChatsResponse)(nil), "chat.GetChatsResponse")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x14, 0x24, 0x7c, 0xa4, 0xe9, 0x75, 0x80, 0x3e, 0x0a, 0x35, 0x99, 0x2a, 0x4f, 0x59, 0x08, 0x02,
	0x46, 0xa6, 0x02, 0xa2, 0x62, 0x60, 0x09, 0x1b, 0x0b, 0x0a, 0xf5, 0x13, 0xed, 0x00, 0x29, 0xb5,
	0xe1, 0x8f, 0xf2, 0x87, 0x90, 0x13, 0x3b, 0x09, 0x04, 0xa9, 0x9b, 0xef, 0xdd, 0xbd, 0x7b, 0xba,
	0x33, 0x30, 0x5f, 0xe4, 0x26, 0x5d, 0xad, 0x0b, 0x53, 0xd0, 0xae, 0x7d, 0xcb, 0x3b, 0x0c, 0xa7,
	0x4a, 0x3d, 0xb0, 0xd6, 0xf9, 0x2b, 0x67, 0xfc, 0xf1, 0xc9, 0xda, 0xd0, 0x18, 0x3d, 0x4b, 0x3e,
	0x2f, 0x95, 0x08, 0x26, 0x41, 0xd2, 0xcf, 0x42, 0x0b, 0xef, 0x15, 0x09, 0xf4, 0xde, 0x2a, 0xa9,
	0xd8, 0x2e, 0x09, 0x0f, 0xe5, 0x08, 0xd4, 0xf6, 0xd1, 0xab, 0xe2, 0x5d, 0xb3, 0x3c, 0x05, 0xcd,
	0xd8, 0xb8, 0xa9, 0xde, 0x64, 0x2f, 0xcf, 0x71, 0xf8, 0x4b, 0x5e, 0xb9, 0x50, 0x8c, 0xc8, 0x9d,
	0xd1, 0x22, 0x98, 0xec, 0x24, 0xfd, 0xac, 0xc6, 0x72, 0x88, 0xfd, 0x19, 0x9b, 0x9b, 0x45, 0x6e,
	0xbc, 0xbd, 0x4c, 0x70, 0xd0, 0x8c, 0x9c, 0xc5, 0x08, 0x7b, 0xf6, 0x86, 0xdf, 0xaf, 0xc0, 0xc5,
	0x77, 0x80, 0x81, 0xd5, 0x3d, 0xf2, 0xfa, 0x6b, 0x39, 0x67, 0x9a, 0x02, 0x4d, 0x08, 0x1a, 0xa7,
	0x65, 0x5b, 0x9d, 0x7a, 0x62, 0xd1, 0x25, 0x5c, 0xde, 0x2d, 0xba, 0xc5, 0xa0, 0x15, 0x81, 0x9c,
	0xb4, 0x5b, 0x42, 0x7c, 0xf2, 0x0f, 0x53, 0xbb, 0x5c, 0x21, 0xf2, 0x11, 0xe8, 0xa8, 0x16, 0xb6,
	0x53, 0xc6, 0xc7, 0x7f, 0xc7, 0x7e, 0xf9, 0x3a, 0x7a, 0x0a, 0xd3, 0x33, 0x4b, 0xbe, 0x84, 0xe5,
	0x4f, 0x5f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x18, 0x71, 0x6d, 0x29, 0xf7, 0x01, 0x00, 0x00,
}
